[project]
name = "python-project-template"
version = "0.1.0"
description = "My cookiecutter template for python projects"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []

[dependency-groups]
dev = [
    "cookiecutter>=2.6.0",
]
